"use strict";
const APP_VERSION="0.7.0";
const DB_NAME="dantestocks-human-annotation-v06";
const DB_VERSION=1;
const STORE_STATE="state", STORE_SNAP="snapshots", STORE_HANDLES="handles";
const EMOTIONS=[
 {code:"trust",name:"Confiança",micro:"confiança · segurança · endosso",center:"Confiança, recomendação ou segurança percebida.",compare:"Alegria → satisfação/comemoração.",not:"uma ação subiu ou alguém comprou."},
 {code:"disgust",name:"Aversão / desprezo",micro:"rejeição · desprezo · aversão",center:"Rejeição, desprezo ou degradação do alvo.",compare:"Raiva → ataque, culpa ou confronto.",not:"o fato financeiro é negativo."},
 {code:"joy",name:"Alegria / satisfação",micro:"prazer · satisfação · comemoração",center:"Prazer, satisfação ou comemoração atual/realizada.",compare:"Expectativa → resultado ainda futuro.",not:"o preço apenas subiu."},
 {code:"sadness",name:"Tristeza / decepção",micro:"perda · decepção · lamento",center:"Lamento, perda ou decepção atual/realizada.",compare:"Medo → dano ainda possível.",not:"há prejuízo factual."},
 {code:"anticipation",name:"Expectativa",micro:"expectativa · prontidão · olhar adiante",center:"Orientação afetiva para o que vem a seguir.",compare:"Medo → futuro ameaçador.",not:"o texto está no futuro."},
 {code:"surprise",name:"Surpresa",micro:"inesperado · espanto · quebra de expectativa",center:"Espanto ou violação de expectativa.",compare:"Expectativa → algo ainda aguardado.",not:"a informação é apenas nova."},
 {code:"anger",name:"Raiva / indignação",micro:"ataque · culpa · indignação",center:"Ataque, culpa, cobrança ou confronto.",compare:"Aversão → desprezo ou rejeição.",not:"há palavrão sem confronto."},
 {code:"fear",name:"Medo / preocupação",micro:"ameaça · preocupação · apreensão",center:"Ameaça, preocupação ou possibilidade de dano.",compare:"Tristeza → dano realizado; Expectativa → futuro sem ameaça.",not:"o post menciona risco técnico."},
 {code:"neutral",name:"Neutro",micro:"nenhum afeto predominante defensável",center:"Nenhuma das oito emoções é defensável como predominante.",compare:"Baixa confiança não significa neutral.",not:"o item é curto ou difícil."}
];
const CONF=[{code:"HIGH",name:"Alta"},{code:"MEDIUM",name:"Média"},{code:"LOW",name:"Baixa"}];
const PILOT_PACKAGE=window.DANTESTOCKS_PILOT_PACKAGE_01||null;
let selectedAnnotator=null;

const DEMO_ASSIGNMENT={"assignment_id":"DEMO_A2_v0.2","annotator_id":"A2-DEMO","pilot_version":"0.2","guideline_version":"0.2","webapp_min_version":"0.4.0","randomization_seed":"DEMO-SEED-20260901","items":[{"post_id":"demo_001","text":"PETR4 fechou a 38,20, alta de 2,1%.","display_source_annotation":true,"source_annotation":{"labels":["joy"],"note":"Emoção marcada como presente na anotação original."}},{"post_id":"demo_002","text":"Finalmente bateu meu alvo! Que maravilha!","display_source_annotation":false},{"post_id":"demo_003","text":"Se perder esse suporte amanhã, isso pode ficar muito feio.","display_source_annotation":true,"source_annotation":{"labels":["fear","anticipation"],"note":"Emoções marcadas como presentes na anotação original."}},{"post_id":"demo_004","text":"A empresa divulgará resultados amanhã após o pregão.","display_source_annotation":false},{"post_id":"demo_005","text":"Essa diretoria precisa responder por isso!","display_source_annotation":true,"source_annotation":{"labels":["anger","disgust"],"note":"Emoções marcadas como presentes na anotação original."}},{"post_id":"demo_006","text":"Como assim subiu 12% hoje?!","display_source_annotation":false},{"post_id":"demo_007","text":"Continuo tranquilo com essa empresa no longo prazo.","display_source_annotation":true,"source_annotation":{"labels":["trust"],"note":"Emoção marcada como presente na anotação original."}},{"post_id":"demo_008","text":"Suporte em 35, resistência em 38.","display_source_annotation":false},{"post_id":"demo_009","text":"Parabéns à diretoria, mais um prejuízo histórico 👏","display_source_annotation":true,"source_annotation":{"labels":["disgust","sadness"],"note":"Emoções marcadas como presentes na anotação original."}},{"post_id":"demo_010","text":"Quero ver se amanhã consegue romper 65.","display_source_annotation":false},{"post_id":"demo_011","text":"Balanço será divulgado amanhã após o pregão.","display_source_annotation":true,"source_annotation":{"labels":["neutral"],"note":"O item foi marcado como neutro na anotação original."}},{"post_id":"demo_012","text":"Estou preocupado com o que pode acontecer depois do anúncio.","display_source_annotation":false}]};
let db=null, assignment=null, assignmentRaw="", assignmentHash="", state=null, currentIndex=0, itemOpenedAt=null, lastTick=Date.now(), timer=null, lastSnapshotCompleted=0, externalDirHandle=null;
const $=id=>document.getElementById(id);

function now(){return new Date().toISOString()}
function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
async function sha256Text(text){const buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE_STATE))d.createObjectStore(STORE_STATE);if(!d.objectStoreNames.contains(STORE_SNAP))d.createObjectStore(STORE_SNAP);if(!d.objectStoreNames.contains(STORE_HANDLES))d.createObjectStore(STORE_HANDLES)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function idbPut(store,key,val){return new Promise((resolve,reject)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).put(val,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function idbGet(store,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store,"readonly");const r=tx.objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function embeddedRawFor(annotatorId){return PILOT_PACKAGE?.assignments_raw?.[annotatorId]||null}
function embeddedAssignmentFor(annotatorId){const raw=embeddedRawFor(annotatorId);if(!raw)return null;try{return JSON.parse(raw)}catch(e){console.error("Embedded assignment inválido",annotatorId,e);return null}}
function completedFromState(assign,saved){if(!assign||!saved?.responses)return 0;return assign.items.reduce((n,it)=>{const r=saved.responses[it.post_id];return n+(r&&r.primary_emotion&&r.confidence?1:0)},0)}
async function getEmbeddedProgress(annotatorId){const assign=embeddedAssignmentFor(annotatorId);if(!assign)return {done:0,total:0,valid:false};const raw=embeddedRawFor(annotatorId);const hash=await sha256Text(raw);const saved=await idbGet(STORE_STATE,assign.assignment_id);if(!saved||saved.assignment_sha256!==hash)return {done:0,total:assign.items.length,valid:true};return {done:completedFromState(assign,saved),total:assign.items.length,valid:true}}
async function renderPackageProfiles(){if(!PILOT_PACKAGE)return;for(const id of ["A1","A2","A3"]){const p=await getEmbeddedProgress(id);const status=$("profileStatus"+id);if(status)status.textContent=p.done?`${p.done}/${p.total} concluídos · continuar`:`${p.total} posts · pronto para começar`}if(selectedAnnotator)await selectAnnotator(selectedAnnotator,true)}
async function selectAnnotator(id,silent=false){if(!["A1","A2","A3"].includes(id)||!embeddedRawFor(id))return;selectedAnnotator=id;document.querySelectorAll('.annotator-profile').forEach(btn=>{const on=btn.dataset.annotator===id;btn.classList.toggle('selected',on);btn.setAttribute('aria-checked',on?'true':'false')});const progress=await getEmbeddedProgress(id);const start=$("startPackage");if(start){start.disabled=false;start.textContent=progress.done?`Continuar Pacote 01 como ${id} →`:`Começar Pacote 01 como ${id} →`}if(!silent){const rb=$("resumeBox");if(progress.done&&rb){rb.classList.remove('hidden');rb.innerHTML=`<strong>Progresso encontrado para ${id}</strong><br><span class="small">${progress.done}/${progress.total} concluídos neste navegador. O botão acima continuará exatamente desse ponto.</span>`}else if(rb){rb.classList.add('hidden');rb.innerHTML=''}}}
async function startSelectedPackage(){if(!selectedAnnotator)return;const raw=embeddedRawFor(selectedAnnotator);if(!raw)return;await loadAssignmentText(raw)}

async function saveState(){if(!state||!assignment)return;state.currentIndex=currentIndex;state.last_updated_at=now();await idbPut(STORE_STATE,assignment.assignment_id,state);$("saveState").textContent="Salvo localmente ✓"}
function responseFor(postId){
  if(!state.responses[postId])state.responses[postId]={post_id:postId,primary_emotion:null,confidence:null,confidence_defaulted:false,confidence_edited:false,ambiguity_flag:false,comment:"",first_opened_at:null,first_saved_at:null,last_saved_at:null,elapsed_seconds:0,revision_count:0};
  const r=state.responses[postId];
  if(!("confidence_defaulted" in r))r.confidence_defaulted=false;
  if(!("confidence_edited" in r))r.confidence_edited=false;
  return r;
}
function completedCount(){return assignment.items.reduce((n,it)=>{const r=state.responses[it.post_id];return n+(r&&r.primary_emotion&&r.confidence?1:0)},0)}
function deferredCount(){return Object.values(state.deferred||{}).filter(Boolean).length}
function allComplete(){return completedCount()===assignment.items.length}
function renderEmotionGrid(){const el=$("emotionGrid");el.innerHTML="";EMOTIONS.forEach((e,i)=>{const lab=document.createElement("label");lab.className="emotion-card";lab.innerHTML=`<input type="radio" name="emotion" value="${e.code}"><span class="emotion-name">${e.name}</span><span class="emotion-code">${e.code}</span><div class="emotion-micro">${e.micro}</div>`;lab.querySelector("input").addEventListener("change",()=>{setEmotion(e.code)});el.appendChild(lab)})}
function renderConfidence(){const el=$("confidenceControl");el.innerHTML="";CONF.forEach(c=>{const lab=document.createElement("label");lab.className="segment";lab.innerHTML=`<input type="radio" name="confidence" value="${c.code}">${c.name}`;lab.querySelector("input").addEventListener("change",()=>{setConfidence(c.code)});el.appendChild(lab)})}
function tickElapsed(){if(!assignment||$("workspace").classList.contains("hidden"))return;const item=assignment.items[currentIndex];if(!item)return;const r=responseFor(item.post_id);const t=Date.now();r.elapsed_seconds+=(t-lastTick)/1000;lastTick=t}
function startTimer(){clearInterval(timer);lastTick=Date.now();timer=setInterval(()=>{tickElapsed();saveState().catch(()=>{})},5000)}
function currentItem(){return assignment.items[currentIndex]}
function renderCurrent(){if(!assignment)return;if(allComplete()){showFinish();return}const item=currentItem();if(!item)return;const r=responseFor(item.post_id);if(!r.first_opened_at)r.first_opened_at=now();if(!r.confidence){r.confidence="MEDIUM";r.confidence_defaulted=true;r.confidence_edited=false;}itemOpenedAt=Date.now();lastTick=Date.now();$("postId").textContent=item.post_id;$("postText").textContent=item.text;
  const sp=$("sourcePanel"), sl=$("sourceLabels"), sn=$("sourceNote");sl.innerHTML="";sn.textContent="";
  if(item.display_source_annotation&&item.source_annotation){sp.classList.remove("hidden");const labs=item.source_annotation.labels||[];if(labs.length){labs.forEach(code=>{const e=EMOTIONS.find(x=>x.code===code);const chip=document.createElement("span");chip.className="source-chip";chip.textContent=e?`${e.name} · ${code}`:code;sl.appendChild(chip)})}else{const chip=document.createElement("span");chip.className="source-chip";chip.textContent="Sem emoção original listada";sl.appendChild(chip)}const note=item.source_annotation.note||"";sn.textContent=(note&&note!=="Anotação original do DANTEStocks; informação de origem, não limita a escolha.")?note:""}else sp.classList.add("hidden");
  document.querySelectorAll('input[name="emotion"]').forEach(inp=>{inp.checked=inp.value===r.primary_emotion;inp.closest('.emotion-card').classList.toggle('selected',inp.checked)});
  document.querySelectorAll('input[name="confidence"]').forEach(inp=>{inp.checked=inp.value===r.confidence;inp.closest('.segment').classList.toggle('selected',inp.checked)});
  $("ambiguity").checked=!!r.ambiguity_flag;$("comment").value=r.comment||"";$("comment").classList.toggle("hidden",!(r.comment&&r.comment.length));$("commentToggle").textContent=$("comment").classList.contains("hidden")?"+ Adicionar comentário":"- Ocultar comentário";
  updateHint(r.primary_emotion);updateControls();updateHeader();saveState().catch(()=>{});startTimer();
}
function updateHint(code){const box=$("dynamicHint");const e=EMOTIONS.find(x=>x.code===code);if(!e){box.innerHTML="<h3>Escolha uma label</h3><p>A pista aparecerá aqui sem revelar nenhuma resposta anterior.</p>";return}box.innerHTML=`<h3>${escapeHtml(e.name)} <span class="emotion-code">${e.code}</span></h3><p><strong>Centro:</strong> ${escapeHtml(e.center)}</p><p><strong>Compare com:</strong> ${escapeHtml(e.compare)}</p><p><strong>Não use só porque:</strong> ${escapeHtml(e.not)}</p>`}
function updateControls(){const r=responseFor(currentItem().post_id);$("saveNext").disabled=!(r.primary_emotion&&r.confidence);$("prevItem").disabled=currentIndex===0;$("deferredCount").textContent=deferredCount()}
function updateHeader(){const done=completedCount();$("progressText").textContent=`${done} / ${assignment.items.length}`;$("assignmentMeta").textContent=`${assignment.annotator_id} · Guideline ${assignment.guideline_version} · App ${APP_VERSION}`;$("deferredCount").textContent=deferredCount()}
async function setEmotion(code){tickElapsed();const r=responseFor(currentItem().post_id);if(r.primary_emotion&&r.primary_emotion!==code)r.revision_count++;r.primary_emotion=code;r.last_saved_at=now();document.querySelectorAll('.emotion-card').forEach(card=>{const inp=card.querySelector('input');card.classList.toggle('selected',inp.value===code);inp.checked=inp.value===code});updateHint(code);updateControls();$("saveState").textContent="Salvando…";await saveState()}
async function setConfidence(code){tickElapsed();const r=responseFor(currentItem().post_id);if(r.confidence&&r.confidence!==code)r.revision_count++;r.confidence=code;r.confidence_edited=true;r.last_saved_at=now();document.querySelectorAll('.segment').forEach(l=>l.classList.toggle('selected',l.querySelector('input').value===code));updateControls();$("saveState").textContent="Salvando…";await saveState()}
async function persistCurrent(finalSave=false){tickElapsed();const r=responseFor(currentItem().post_id);r.ambiguity_flag=$("ambiguity").checked;r.comment=$("comment").value.trim();r.last_saved_at=now();if(finalSave&&!r.first_saved_at)r.first_saved_at=now();await saveState();if(finalSave)await maybeSnapshot()}
async function maybeSnapshot(){const done=completedCount();if(done>=10&&done%10===0&&done>lastSnapshotCompleted){await createSnapshot(done,true);lastSnapshotCompleted=done;state.last_snapshot_completed=done;await saveState()}}
async function createSnapshot(done,auto=false){const snap=await buildExportPayload();snap.snapshot={completed_count:done,created_at:now(),automatic:auto};const name=`${assignment.annotator_id}_PILOT_CHECKPOINT_${String(done).padStart(4,"0")}.json`;await idbPut(STORE_SNAP,`${assignment.assignment_id}:${String(done).padStart(4,"0")}`,snap);$("snapshotStatus").textContent=`Snapshot ${done} salvo automaticamente no navegador.`;if(externalDirHandle){try{if(await verifyPermission(externalDirHandle,true)){const fh=await externalDirHandle.getFileHandle(name,{create:true});const w=await fh.createWritable();await w.write(JSON.stringify(snap,null,2));await w.close();$("snapshotStatus").textContent=`Snapshot ${done} salvo no navegador e na pasta de backup.`}}catch(e){console.warn(e);$("snapshotStatus").textContent=`Snapshot ${done} salvo no navegador; backup externo indisponível.`}}}
async function verifyPermission(handle,write=false){const opts={mode:write?"readwrite":"read"};if((await handle.queryPermission(opts))==="granted")return true;return (await handle.requestPermission(opts))==="granted"}
function renderBackupSetupStatus(){
 const badge=$("backupSetupBadge"), btn=$("chooseBackupDir");
 if(!badge||!btn)return;
 if(externalDirHandle){badge.textContent="Ativado ✓";badge.className="backup-status-badge active";btn.textContent="Trocar pasta de backup";btn.classList.add("configured");$("backupSupport").textContent="Checkpoints externos serão gravados automaticamente a cada 10 decisões.";return}
 btn.classList.remove("configured");
 if(!window.showDirectoryPicker){badge.textContent="Backup interno ativo";badge.className="backup-status-badge internal";btn.textContent="Backup externo não suportado neste navegador";btn.disabled=true;$("backupSupport").textContent="O autosave e os snapshots internos continuam funcionando normalmente.";return}
 badge.textContent="Não configurado";badge.className="backup-status-badge pending";btn.textContent="Ativar backup automático →";btn.disabled=false;$("backupSupport").textContent="Escolha uma pasta uma vez; depois o backup é automático.";
}
async function chooseBackup(){if(!window.showDirectoryPicker){renderBackupSetupStatus();return}try{externalDirHandle=await window.showDirectoryPicker({mode:"readwrite"});await idbPut(STORE_HANDLES,"backupDir",externalDirHandle);renderBackupSetupStatus()}catch(e){if(e.name!=="AbortError"){$("backupSupport").textContent="Não foi possível ativar a pasta; snapshots internos continuam ativos."}renderBackupSetupStatus()}}
async function buildExportPayload(){return {format:"DANTEStocks_HUMAN_PILOT_RESPONSE_v0.3",assignment_id:assignment.assignment_id,assignment_sha256:assignmentHash,annotator_id:assignment.annotator_id,pilot_version:assignment.pilot_version,guideline_version:assignment.guideline_version,webapp_version:APP_VERSION,exported_at:now(),responses:assignment.items.map((it,i)=>{const r=responseFor(it.post_id);return {post_id:it.post_id,random_order:i+1,primary_emotion:r.primary_emotion,confidence:r.confidence,confidence_defaulted:!!r.confidence_defaulted,confidence_edited:!!r.confidence_edited,ambiguity_flag:!!r.ambiguity_flag,comment:r.comment||"",first_opened_at:r.first_opened_at,first_saved_at:r.first_saved_at,last_saved_at:r.last_saved_at,elapsed_seconds:Math.round((r.elapsed_seconds||0)*10)/10,revision_count:r.revision_count||0}})}}
function csvEscape(v){const s=String(v??"");return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
async function buildCSV(){const p=await buildExportPayload();const cols=["assignment_id","annotator_id","post_id","random_order","primary_emotion","confidence","confidence_defaulted","confidence_edited","ambiguity_flag","comment","guideline_version","webapp_version","first_opened_at","first_saved_at","last_saved_at","elapsed_seconds","revision_count"];const rows=[cols.join(",")];p.responses.forEach(r=>rows.push(cols.map(c=>csvEscape(c in r?r[c]:({assignment_id:p.assignment_id,annotator_id:p.annotator_id,guideline_version:p.guideline_version,webapp_version:p.webapp_version}[c]??""))).join(",")));return rows.join("\n")+"\n"}
function downloadText(filename,text,type="text/plain"){const b=new Blob([text],{type});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function exportCheckpointManual(){if(!assignment)return;await persistCurrent(false);const p=await buildExportPayload();p.snapshot={completed_count:completedCount(),created_at:now(),automatic:false};downloadText(`${assignment.annotator_id}_PILOT_CHECKPOINT_${String(completedCount()).padStart(4,"0")}.json`,JSON.stringify(p,null,2),"application/json")}
async function goNext(){await persistCurrent(true);const doneBefore=completedCount();delete state.deferred[currentItem().post_id];if(allComplete()){showFinish();return}let idx=currentIndex+1;while(idx<assignment.items.length){const r=state.responses[assignment.items[idx].post_id];if(!(r&&r.primary_emotion&&r.confidence)){currentIndex=idx;renderCurrent();return}idx++}const pend=assignment.items.findIndex(it=>{const r=state.responses[it.post_id];return !(r&&r.primary_emotion&&r.confidence)});currentIndex=pend>=0?pend:0;renderCurrent()}
async function deferCurrent(){await persistCurrent(false);state.deferred[currentItem().post_id]=true;await saveState();let idx=currentIndex+1;if(idx>=assignment.items.length)idx=0;let tries=0;while(tries<assignment.items.length){const it=assignment.items[idx], r=state.responses[it.post_id];if(!(r&&r.primary_emotion&&r.confidence)&&it.post_id!==currentItem().post_id){currentIndex=idx;renderCurrent();return}idx=(idx+1)%assignment.items.length;tries++}updateHeader()}
function showFinish(){clearInterval(timer);$("workspace").classList.add("hidden");$("onboarding").classList.add("hidden");$("finish").classList.remove("hidden");$("finishSummary").textContent=`${assignment.items.length} / ${assignment.items.length} concluídos · 0 pendentes.`;$("progressText").textContent=`${assignment.items.length} / ${assignment.items.length}`}
function validateAssignment(obj){const errors=[];for(const k of ["assignment_id","annotator_id","pilot_version","guideline_version","items"])if(!obj||!(k in obj))errors.push(`campo ausente: ${k}`);if(!Array.isArray(obj?.items)||!obj.items.length)errors.push("items vazio");const ids=new Set();(obj?.items||[]).forEach((it,i)=>{if(!it.post_id||typeof it.text!=="string"||typeof it.display_source_annotation!=="boolean")errors.push(`item ${i+1} inválido`);if(ids.has(it.post_id))errors.push(`post_id duplicado: ${it.post_id}`);ids.add(it.post_id);if(it.display_source_annotation&&!it.source_annotation)errors.push(`item ${it.post_id}: source_annotation ausente`);if(!it.display_source_annotation&&("source_annotation" in it))errors.push(`item ${it.post_id}: blind contém source_annotation (vazamento)`) });return errors}
async function loadAssignmentText(text){let obj;try{obj=JSON.parse(text)}catch(e){alert("JSON de assignment inválido.");return}const errs=validateAssignment(obj);if(errs.length){alert("Assignment recusado:\n"+errs.join("\n"));return}assignment=obj;assignmentRaw=text;assignmentHash=await sha256Text(text);let saved=await idbGet(STORE_STATE,assignment.assignment_id);if(saved&&saved.assignment_sha256===assignmentHash){state=saved;currentIndex=saved.currentIndex||0;lastSnapshotCompleted=saved.last_snapshot_completed||0}else{state={assignment_id:assignment.assignment_id,assignment_sha256:assignmentHash,annotator_id:assignment.annotator_id,created_at:now(),last_updated_at:now(),currentIndex:0,last_snapshot_completed:0,deferred:{},responses:{}};currentIndex=0;lastSnapshotCompleted=0;await saveState()}$("onboarding").classList.add("hidden");$("finish").classList.add("hidden");$("workspace").classList.remove("hidden");renderCurrent()}
async function importCheckpoint(text){let cp;try{cp=JSON.parse(text)}catch(e){alert("Checkpoint inválido.");return}if(!cp.assignment_id||!cp.assignment_sha256||!Array.isArray(cp.responses)){alert("Checkpoint sem campos obrigatórios.");return}
 let target=cp.annotator_id;
 if(!["A1","A2","A3"].includes(target)){const m=String(cp.assignment_id).match(/_(A[123])_/);target=m?m[1]:null}
 if(!assignment&&target&&embeddedRawFor(target)){selectedAnnotator=target;await loadAssignmentText(embeddedRawFor(target))}
 if(!assignment){alert("Não foi possível identificar A1, A2 ou A3 a partir deste checkpoint.");return}
 if(cp.assignment_id!==assignment.assignment_id||cp.assignment_sha256!==assignmentHash){alert("Checkpoint não pertence ao Pacote 01 selecionado ou o hash não coincide.");return}
 cp.responses.forEach(r=>{state.responses[r.post_id]={...responseFor(r.post_id),...r}});state.last_updated_at=now();await saveState();renderCurrent();alert("Checkpoint recuperado com sucesso.")}
function openGuide(kind){const frame=$("guideFrame");$("guideTitle").textContent=kind==="quick"?"Guia rápido":"Guideline completo";frame.onload=()=>{try{frame.contentDocument.documentElement.dataset.theme=document.documentElement.dataset.theme||"light"}catch(e){}};frame.src=kind==="quick"?"guides/quick.html":"guides/full.html";$("guideModal").classList.remove("hidden")}
function applyTheme(theme){
  const resolved=theme==="dark"?"dark":"light";
  document.documentElement.dataset.theme=resolved;
  localStorage.setItem("dantestocks-theme",resolved);
  const btn=$("themeToggle");
  if(btn){btn.textContent=resolved==="dark"?"☀ Claro":"☾ Escuro";btn.setAttribute("aria-label",resolved==="dark"?"Ativar modo claro":"Ativar modo escuro");}
  const frame=$("guideFrame");
  try{if(frame?.contentDocument?.documentElement)frame.contentDocument.documentElement.dataset.theme=resolved}catch(e){}
}
function initTheme(){
  const saved=localStorage.getItem("dantestocks-theme");
  const initial=saved||(window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");
  applyTheme(initial);
}
function toggleTheme(){applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");}

async function init(){initTheme();db=await openDB();renderEmotionGrid();renderConfidence();externalDirHandle=await idbGet(STORE_HANDLES,"backupDir");renderBackupSetupStatus();
 if(!PILOT_PACKAGE||PILOT_PACKAGE.generated===false||!PILOT_PACKAGE.assignments_raw||Object.keys(PILOT_PACKAGE.assignments_raw).length!==3){
   document.querySelectorAll('.annotator-profile').forEach(btn=>btn.disabled=true);
   const start=$('startPackage'); if(start){start.disabled=true;start.textContent='Pilot404 ainda não materializado';}
   const rb=$('resumeBox'); if(rb){rb.classList.remove('hidden');rb.innerHTML='<strong>Build necessário antes da publicação.</strong><br><span class="small">Execute <code>BUILD_AND_DEPLOY.sh</code>. O script obtém o UD canônico, materializa os 404 e só então publica.</span>';}
   $('saveState').textContent='Build pendente';
 }
 document.querySelectorAll('.annotator-profile').forEach(btn=>btn.addEventListener('click',()=>selectAnnotator(btn.dataset.annotator)));
 $("startPackage").onclick=startSelectedPackage;
 if($("themeToggle"))$("themeToggle").onclick=toggleTheme;
 $("checkpointInput").addEventListener("change",async e=>{const f=e.target.files[0];if(f)await importCheckpoint(await f.text());e.target.value=""});
 $("loadDemo").onclick=async()=>{await loadAssignmentText(JSON.stringify(DEMO_ASSIGNMENT))};
 $("chooseBackupDir").onclick=chooseBackup;$("ambiguity").onchange=async()=>{responseFor(currentItem().post_id).ambiguity_flag=$("ambiguity").checked;await saveState()};
 $("commentToggle").onclick=()=>{$("comment").classList.toggle("hidden");$("commentToggle").textContent=$("comment").classList.contains("hidden")?"+ Adicionar comentário":"- Ocultar comentário";if(!$("comment").classList.contains("hidden"))$("comment").focus()};
 $("comment").oninput=async()=>{responseFor(currentItem().post_id).comment=$("comment").value;await saveState()};
 $("saveNext").onclick=goNext;$("deferItem").onclick=deferCurrent;$("prevItem").onclick=async()=>{await persistCurrent(false);if(currentIndex>0){currentIndex--;renderCurrent()}};
 $("deferredBtn").onclick=async()=>{const idx=assignment.items.findIndex(it=>state.deferred[it.post_id]);if(idx>=0){await persistCurrent(false);currentIndex=idx;renderCurrent()}};
 $("exportCheckpoint").onclick=exportCheckpointManual;$("quickGuideBtn").onclick=()=>openGuide("quick");$("fullGuideBtn").onclick=()=>openGuide("full");$("closeGuide").onclick=()=>{$("guideModal").classList.add("hidden");$("guideFrame").src="about:blank"};
 $("downloadJSON").onclick=async()=>{const p=await buildExportPayload();downloadText(`${assignment.annotator_id}_HUMAN_PILOT_FINAL.json`,JSON.stringify(p,null,2),"application/json")};
 $("downloadCSV").onclick=async()=>downloadText(`${assignment.annotator_id}_HUMAN_PILOT_FINAL.csv`,await buildCSV(),"text/csv;charset=utf-8");
 $("downloadSHA").onclick=async()=>{const p=await buildExportPayload();const txt=JSON.stringify(p,null,2);const h=await sha256Text(txt);downloadText(`${assignment.annotator_id}_HUMAN_PILOT_FINAL.sha256.txt`,`${h}  ${assignment.annotator_id}_HUMAN_PILOT_FINAL.json\n`)};
 document.addEventListener("keydown",e=>{if($("workspace").classList.contains("hidden")||!assignment)return;const tag=document.activeElement.tagName;if(tag==="TEXTAREA")return;if(e.key>="1"&&e.key<="9"){document.querySelectorAll('input[name="emotion"]')[Number(e.key)-1].click()}const m={h:"HIGH",H:"HIGH",m:"MEDIUM",M:"MEDIUM",l:"LOW",L:"LOW"};if(m[e.key])document.querySelector(`input[name="confidence"][value="${m[e.key]}"]`).click();if(e.key==="a"||e.key==="A")$("ambiguity").click();if(e.key==="Enter"&&!$("saveNext").disabled)$("saveNext").click();if(e.key==="Escape"&&!$("guideModal").classList.contains("hidden"))$("closeGuide").click()});
 window.addEventListener("beforeunload",()=>{tickElapsed()});
 await renderPackageProfiles();
 const params=new URLSearchParams(location.search);const aid=params.get("annotator")?.toUpperCase();if(["A1","A2","A3"].includes(aid)){await selectAnnotator(aid);if(params.get("start")==="1")await startSelectedPackage()}
 if(params.get("demo")==="1"){try{await loadAssignmentText(JSON.stringify(DEMO_ASSIGNMENT))}catch(e){console.warn("demo autoload failed",e)}}
}
init().catch(e=>{console.error(e);$("saveState").textContent="Erro ao iniciar"});
